name: Templates

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  # template-typescript:
  #   name: "Template: typescript"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1

  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: "14"

  #     - run: git switch --orphan typescript

  #     - run: npx degit sveltejs/template --force
  #     - run: node scripts/setupTypeScript.js
  #     - run: yarn set version berry
  #     - run: yarn

  #     - run: |
  #         yarn add -D svelte-language-server
  #         yarn dlx @yarnpkg/pnpify --sdk vscode
  #         yarn plugin import typescript

  #     - run: |
  #         cat >>.gitignore <<EOL

  #         .yarn/*
  #         !.yarn/cache
  #         !.yarn/releases
  #         !.yarn/plugins
  #         !.yarn/sdks
  #         !.yarn/versions
  #         EOL

  #     - run: |
  #         cat >>.gitattributes <<EOL
  #         /.yarn/** linguist-vendored
  #         EOL

  #     - run: |
  #         git config --global user.email "github-actions@users.noreply.github.com"
  #         git config --global user.name "github-actions"
  #         git add .
  #         git commit -m "[automated] Update template"
  #         git push origin HEAD --force

  # template-javascript:
  #   name: "Template: javascript"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1

  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: "14"

  #     - run: git switch --orphan javascript

  #     - run: npx degit sveltejs/template --force
  #     - run: rm scripts/setupTypeScript.js
  #     - run: yarn set version berry
  #     - run: yarn

  #     - run: |
  #         yarn add -D svelte-language-server
  #         yarn dlx @yarnpkg/pnpify --sdk vscode

  #     - run: |
  #         cat >>.gitignore <<EOL

  #         .yarn/*
  #         !.yarn/cache
  #         !.yarn/releases
  #         !.yarn/plugins
  #         !.yarn/sdks
  #         !.yarn/versions
  #         EOL

  #     - run: |
  #         cat >>.gitattributes <<EOL
  #         /.yarn/** linguist-vendored
  #         EOL

  #     - run: |
  #         git config --global user.email "github-actions@users.noreply.github.com"
  #         git config --global user.name "github-actions"
  #         git add .
  #         git commit -m "[automated] Update template"
  #         git push origin HEAD --force

  # template-sapper-typescript:
  #   name: "Template: sapper-typescript"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1

  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: "14"

  #     - run: |
  #         sudo mkdir -p /var/svelte-template/scripts
  #         sudo cp -r scripts /var/svelte-template

  #     - run: git switch --orphan sapper-typescript

  #     - run: npx degit sveltejs/sapper-template#rollup --force
  #     - run: node scripts/setupTypeScript.js
  #     - run: yarn set version berry
  #     - run: yarn

  #     - run: yarn add -D @rollup/plugin-alias
  #     - run: node /var/svelte-template/scripts/fix-sapper-pnp.js

  #     - run: |
  #         yarn add -D svelte-language-server
  #         yarn dlx @yarnpkg/pnpify --sdk vscode
  #         yarn plugin import typescript

  #     - run: |
  #         cat >>.gitignore <<EOL

  #         .yarn/*
  #         !.yarn/cache
  #         !.yarn/releases
  #         !.yarn/plugins
  #         !.yarn/sdks
  #         !.yarn/versions
  #         EOL

  #     - run: |
  #         cat >>.gitattributes <<EOL
  #         /.yarn/** linguist-vendored
  #         EOL

  #     - run: |
  #         git config --global user.email "github-actions@users.noreply.github.com"
  #         git config --global user.name "github-actions"
  #         git add .
  #         git commit -m "[automated] Update template"
  #         git push origin HEAD --force

  # template-sapper-javascript:
  #   name: "Template: sapper-javascript"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1

  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: "14"

  #     - run: |
  #         sudo mkdir -p /var/svelte-template/scripts
  #         sudo cp -r scripts /var/svelte-template

  #     - run: git switch --orphan sapper-javascript

  #     - run: npx degit sveltejs/sapper-template#rollup --force
  #     - run: rm scripts/setupTypeScript.js
  #     - run: yarn set version berry
  #     - run: yarn

  #     - run: yarn add -D @rollup/plugin-alias
  #     - run: node /var/svelte-template/scripts/fix-sapper-pnp.js

  #     - run: |
  #         yarn add -D svelte-language-server
  #         yarn dlx @yarnpkg/pnpify --sdk vscode

  #     - run: |
  #         cat >>.gitignore <<EOL

  #         .yarn/*
  #         !.yarn/cache
  #         !.yarn/releases
  #         !.yarn/plugins
  #         !.yarn/sdks
  #         !.yarn/versions
  #         EOL

  #     - run: |
  #         cat >>.gitattributes <<EOL
  #         /.yarn/** linguist-vendored
  #         EOL

  #     - run: |
  #         git config --global user.email "github-actions@users.noreply.github.com"
  #         git config --global user.name "github-actions"
  #         git add .
  #         git commit -m "[automated] Update template"
  #         git push origin HEAD --force

  # template-typescript-tailwind:
  #   name: "Template: typescript-tailwind"
  #   runs-on: ubuntu-latest
  #   needs: [template-typescript]
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1

  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: "14"

  #     - run: |
  #         sudo mkdir -p /var/svelte-template/scripts
  #         sudo cp -r scripts /var/svelte-template

  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1
  #         ref: typescript

  #     - run: git switch --force-create typescript-tailwind

  #     - run: yarn add -D svelte-preprocess tailwindcss autoprefixer postcss-nesting postcss
  #     - run: node /var/svelte-template/scripts/setup-tailwind

  #     - run: |
  #         git config --global user.email "github-actions@users.noreply.github.com"
  #         git config --global user.name "github-actions"
  #         git add .
  #         git commit -m "[automated] Update template"
  #         git push origin HEAD --force

  # template-sapper-typescript-tailwind:
  #   name: "Template: sapper-typescript-tailwind"
  #   runs-on: ubuntu-latest
  #   needs: [template-sapper-typescript]
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1

  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: "14"

  #     - run: |
  #         sudo mkdir -p /var/svelte-template/scripts
  #         sudo cp -r scripts /var/svelte-template

  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1
  #         ref: sapper-typescript

  #     - run: git switch --force-create sapper-typescript-tailwind

  #     - run: yarn add -D svelte-preprocess tailwindcss autoprefixer postcss-nesting postcss
  #     - run: node /var/svelte-template/scripts/setup-tailwind

  #     - run: |
  #         git config --global user.email "github-actions@users.noreply.github.com"
  #         git config --global user.name "github-actions"
  #         git add .
  #         git commit -m "[automated] Update template"
  #         git push origin HEAD --force

  template-snowpack-javascript:
    name: "template: snowpack-javascript"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: |
          sudo mkdir -p /var/svelte-template/scripts
          sudo cp -r scripts /var/svelte-template

      - run: git switch --orphan snowpack-javascript

      - run: yarn set version berry
      - run: yarn dlx create-snowpack-app . --template @snowpack/app-template-svelte --force --use-yarn
      - run: |
          cat >>.gitignore <<EOL

          .yarn/*
          !.yarn/cache
          !.yarn/releases
          !.yarn/plugins
          !.yarn/sdks
          !.yarn/versions
          EOL
      - run: |
          cat >>.gitattributes <<EOL
          /.yarn/** linguist-vendored
          EOL

      - run: |
          yarn add -D prettier prettier-plugin-svelte

      - run: |
          cat >>prettier.config.js <<EOL
          /** @type {import("prettier").Options } */
          module.exports = {
              semi: true,
              singleQuote: false,
              printWidth: 120,
              useTabs: false,
              tabWidth: 4,
              plugins: [require("prettier-plugin-svelte")],
          };
          EOL

      - run: |
          cat >>.prettierignore <<EOL
          .yarn/
          build/
          node_modules/
          .pnp.js
          EOL

      - run: |
          cat >>.editorconfig <<EOL
          root = true

          [*]
          indent_style = space
          indent_size = 4
          charset = utf-8
          trim_trailing_whitespace = true
          insert_final_newline = true
          end_of_line = lf

          [*.{yml,yaml,md}]
          indent_size = 2

          [Makefile]
          indent_style = tab
          EOL

      - run: |
          yarn add -D svelte-hmr svelte-language-server @snowpack/plugin-webpack
          node /var/svelte-template/scripts/add-snowpack-plugins @snowpack/plugin-webpack
          yarn dlx @yarnpkg/pnpify --sdk vscode

      - run:
          node /var/svelte-template/scripts/add-prettier-format
          yarn format

      - run: yarn test

      - run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "github-actions"
          git add .
          git commit -m "[automated] Update template"
          git push origin HEAD --force

  template-snowpack-typescript:
    name: "template: snowpack-typescript"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: |
          sudo mkdir -p /var/svelte-template/scripts
          sudo cp -r scripts /var/svelte-template

      - run: git switch --orphan snowpack-typescript

      - run: yarn set version berry
      - run: yarn dlx create-snowpack-app . --template @snowpack/app-template-svelte-typescript --force --use-yarn
      - run: |
          cat >>.gitignore <<EOL

          .yarn/*
          !.yarn/cache
          !.yarn/releases
          !.yarn/plugins
          !.yarn/sdks
          !.yarn/versions
          EOL
      - run: |
          cat >>.gitattributes <<EOL
          /.yarn/** linguist-vendored
          EOL

      - run: |
          yarn add -D prettier prettier-plugin-svelte

      - run: |
          cat >>prettier.config.js <<EOL
          /** @type {import("prettier").Options } */
          module.exports = {
              semi: true,
              singleQuote: false,
              printWidth: 120,
              useTabs: false,
              tabWidth: 4,
              plugins: [require("prettier-plugin-svelte")],
          };
          EOL

      - run: |
          cat >>.prettierignore <<EOL
          .yarn/
          build/
          node_modules/
          .pnp.js
          EOL

      - run: |
          cat >>.editorconfig <<EOL
          root = true

          [*]
          indent_style = space
          indent_size = 4
          charset = utf-8
          trim_trailing_whitespace = true
          insert_final_newline = true
          end_of_line = lf

          [*.{yml,yaml,md}]
          indent_size = 2

          [Makefile]
          indent_style = tab
          EOL

      - run: |
          yarn add -D svelte-hmr svelte-language-server @snowpack/plugin-webpack
          yarn plugin import typescript
          node /var/svelte-template/scripts/add-snowpack-plugins @snowpack/plugin-webpack
          yarn dlx @yarnpkg/pnpify --sdk vscode

      - run:
          node /var/svelte-template/scripts/add-prettier-format
          yarn format

      - run: yarn test

      - run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "github-actions"
          git add .
          git commit -m "[automated] Update template"
          git push origin HEAD --force
