name: Templates

on:
  workflow_dispatch:

jobs:
  template-typescript:
    name: "Template: typescript"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - run: git switch --orphan typescript

      - run: npx degit sveltejs/template --force
      - run: node scripts/setupTypeScript.js
      - run: yarn set version berry
      - run: yarn
      - run: |
          cat >>.gitignore <<EOL

          .yarn/*
          !.yarn/cache
          !.yarn/releases
          !.yarn/plugins
          !.yarn/sdks
          !.yarn/versions
          EOL

      - run: |
          cat >>.gitattributes <<EOL
          /.yarn/** linguist-vendored
          EOL

      - run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "github-actions"
          git add .
          git commit -m "[automated] Update template"
          git push origin HEAD --force
