name: Templates

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"

env:
    SCRIPTS: /var/svelte-template/scripts

jobs:
    # template-typescript:
    #     name: "Template: typescript"
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v2
    #           with:
    #               fetch-depth: 1

    #         - uses: actions/setup-node@v2
    #           with:
    #               node-version: "14"

    #         - run: |
    #               sudo mkdir -p $SCRIPTS
    #               sudo cp -r scripts /var/svelte-template

    #         - run: git switch --orphan typescript

    #         - run: npx degit sveltejs/template --force
    #         - run: node scripts/setupTypeScript.js
    #         - run: yarn set version berry
    #         - run: yarn

    #         - run: |
    #               yarn add -D svelte-language-server
    #               yarn dlx @yarnpkg/pnpify --sdk vscode
    #               yarn plugin import typescript

    #         - run: |
    #               cat >>.gitignore <<EOL

    #               .yarn/*
    #               !.yarn/cache
    #               !.yarn/releases
    #               !.yarn/plugins
    #               !.yarn/sdks
    #               !.yarn/versions
    #               EOL

    #         - run: |
    #               cat >>.gitattributes <<EOL
    #               /.yarn/** linguist-vendored
    #               EOL

    #         - run: node $SCRIPTS/add-prettier
    #         - run: node $SCRIPTS/add-lint-staged

    #         - run: yarn dlx @yarnpkg/pnpify --sdk vscode
    #         - run: yarn format

    #         - run: |
    #               git config --global user.email "github-actions@users.noreply.github.com"
    #               git config --global user.name "github-actions"
    #               git add .
    #               git commit -m "[automated] Update template"
    #               git push origin HEAD --force

    # template-javascript:
    #     name: "Template: javascript"
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v2
    #           with:
    #               fetch-depth: 1

    #         - uses: actions/setup-node@v2
    #           with:
    #               node-version: "14"

    #         - run: |
    #               sudo mkdir -p $SCRIPTS
    #               sudo cp -r scripts /var/svelte-template

    #         - run: git switch --orphan javascript

    #         - run: npx degit sveltejs/template --force
    #         - run: rm scripts/setupTypeScript.js
    #         - run: yarn set version berry
    #         - run: yarn

    #         - run: |
    #               yarn add -D svelte-language-server
    #               yarn dlx @yarnpkg/pnpify --sdk vscode

    #         - run: |
    #               cat >>.gitignore <<EOL

    #               .yarn/*
    #               !.yarn/cache
    #               !.yarn/releases
    #               !.yarn/plugins
    #               !.yarn/sdks
    #               !.yarn/versions
    #               EOL

    #         - run: |
    #               cat >>.gitattributes <<EOL
    #               /.yarn/** linguist-vendored
    #               EOL

    #         - run: node $SCRIPTS/add-prettier
    #         - run: node $SCRIPTS/add-lint-staged

    #         - run: yarn dlx @yarnpkg/pnpify --sdk vscode
    #         - run: yarn format

    #         - run: |
    #               git config --global user.email "github-actions@users.noreply.github.com"
    #               git config --global user.name "github-actions"
    #               git add .
    #               git commit -m "[automated] Update template"
    #               git push origin HEAD --force

    # template-sapper-typescript:
    #     name: "Template: sapper-typescript"
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v2
    #           with:
    #               fetch-depth: 1

    #         - uses: actions/setup-node@v2
    #           with:
    #               node-version: "14"

    #         - run: |
    #               sudo mkdir -p $SCRIPTS
    #               sudo cp -r scripts /var/svelte-template

    #         - run: git switch --orphan sapper-typescript

    #         - run: npx degit sveltejs/sapper-template#rollup --force
    #         - run: node scripts/setupTypeScript.js
    #         - run: yarn set version berry
    #         - run: yarn

    #         - run: yarn add -D @rollup/plugin-alias
    #         - run: node $SCRIPTS/fix-sapper-pnp.js

    #         - run: |
    #               yarn add -D svelte-language-server
    #               yarn dlx @yarnpkg/pnpify --sdk vscode
    #               yarn plugin import typescript

    #         - run: |
    #               cat >>.gitignore <<EOL

    #               .yarn/*
    #               !.yarn/cache
    #               !.yarn/releases
    #               !.yarn/plugins
    #               !.yarn/sdks
    #               !.yarn/versions
    #               EOL

    #         - run: |
    #               cat >>.gitattributes <<EOL
    #               /.yarn/** linguist-vendored
    #               EOL

    #         - run: node $SCRIPTS/add-prettier
    #         - run: node $SCRIPTS/add-lint-staged

    #         - run: yarn dlx @yarnpkg/pnpify --sdk vscode
    #         - run: yarn format

    #         - run: |
    #               git config --global user.email "github-actions@users.noreply.github.com"
    #               git config --global user.name "github-actions"
    #               git add .
    #               git commit -m "[automated] Update template"
    #               git push origin HEAD --force

    # template-sapper-javascript:
    #     name: "Template: sapper-javascript"
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v2
    #           with:
    #               fetch-depth: 1

    #         - uses: actions/setup-node@v2
    #           with:
    #               node-version: "14"

    #         - run: |
    #               sudo mkdir -p $SCRIPTS
    #               sudo cp -r scripts /var/svelte-template

    #         - run: git switch --orphan sapper-javascript

    #         - run: npx degit sveltejs/sapper-template#rollup --force
    #         - run: rm scripts/setupTypeScript.js
    #         - run: yarn set version berry
    #         - run: yarn

    #         - run: yarn add -D @rollup/plugin-alias
    #         - run: node $SCRIPTS/fix-sapper-pnp.js

    #         - run: |
    #               yarn add -D svelte-language-server
    #               yarn dlx @yarnpkg/pnpify --sdk vscode

    #         - run: |
    #               cat >>.gitignore <<EOL

    #               .yarn/*
    #               !.yarn/cache
    #               !.yarn/releases
    #               !.yarn/plugins
    #               !.yarn/sdks
    #               !.yarn/versions
    #               EOL

    #         - run: |
    #               cat >>.gitattributes <<EOL
    #               /.yarn/** linguist-vendored
    #               EOL

    #         - run: node $SCRIPTS/add-prettier
    #         - run: node $SCRIPTS/add-lint-staged

    #         - run: yarn dlx @yarnpkg/pnpify --sdk vscode
    #         - run: yarn format

    #         - run: |
    #               git config --global user.email "github-actions@users.noreply.github.com"
    #               git config --global user.name "github-actions"
    #               git add .
    #               git commit -m "[automated] Update template"
    #               git push origin HEAD --force

    # template-typescript-tailwind:
    #     name: "Template: typescript-tailwind"
    #     runs-on: ubuntu-latest
    #     needs: [template-typescript]
    #     steps:
    #         - uses: actions/checkout@v2
    #           with:
    #               fetch-depth: 1

    #         - uses: actions/setup-node@v2
    #           with:
    #               node-version: "14"

    #         - run: |
    #               sudo mkdir -p $SCRIPTS
    #               sudo cp -r scripts /var/svelte-template

    #         - uses: actions/checkout@v2
    #           with:
    #               fetch-depth: 1
    #               ref: typescript

    #         - run: git switch --force-create typescript-tailwind

    #         - run: yarn add -D svelte-preprocess tailwindcss autoprefixer postcss-nesting postcss
    #         - run: node $SCRIPTS/setup-tailwind

    #         - run: |
    #               git config --global user.email "github-actions@users.noreply.github.com"
    #               git config --global user.name "github-actions"
    #               git add .
    #               git commit -m "[automated] Update template"
    #               git push origin HEAD --force

    # template-sapper-typescript-tailwind:
    #     name: "Template: sapper-typescript-tailwind"
    #     runs-on: ubuntu-latest
    #     needs: [template-sapper-typescript]
    #     steps:
    #         - uses: actions/checkout@v2
    #           with:
    #               fetch-depth: 1

    #         - uses: actions/setup-node@v2
    #           with:
    #               node-version: "14"

    #         - run: |
    #               sudo mkdir -p $SCRIPTS
    #               sudo cp -r scripts /var/svelte-template

    #         - uses: actions/checkout@v2
    #           with:
    #               fetch-depth: 1
    #               ref: sapper-typescript

    #         - run: git switch --force-create sapper-typescript-tailwind

    #         - run: yarn add -D svelte-preprocess tailwindcss autoprefixer postcss-nesting postcss
    #         - run: node $SCRIPTS/setup-tailwind

    #         - run: |
    #               git config --global user.email "github-actions@users.noreply.github.com"
    #               git config --global user.name "github-actions"
    #               git add .
    #               git commit -m "[automated] Update template"
    #               git push origin HEAD --force

    # template-snowpack-javascript:
    #     name: "template: snowpack-javascript"
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v2
    #           with:
    #               fetch-depth: 1

    #         - uses: actions/setup-node@v2
    #           with:
    #               node-version: "14"

    #         - run: |
    #               sudo mkdir -p $SCRIPTS
    #               sudo cp -r scripts /var/svelte-template

    #         - run: git switch --orphan snowpack-javascript

    #         - run: yarn set version berry
    #         - run: yarn dlx create-snowpack-app . --template @snowpack/app-template-svelte --force --use-yarn
    #         - run: |
    #               cat >>.gitignore <<EOL

    #               .yarn/*
    #               !.yarn/cache
    #               !.yarn/releases
    #               !.yarn/plugins
    #               !.yarn/sdks
    #               !.yarn/versions
    #               EOL
    #         - run: |
    #               cat >>.gitattributes <<EOL
    #               /.yarn/** linguist-vendored
    #               EOL

    #         - run: |
    #               yarn add -D svelte-hmr svelte-language-server @snowpack/plugin-webpack
    #               node $SCRIPTS/add-snowpack-plugins @snowpack/plugin-webpack
    #               yarn dlx @yarnpkg/pnpify --sdk vscode

    #         - run: node $SCRIPTS/add-prettier
    #         - run: node $SCRIPTS/add-lint-staged
    #         - run: node $SCRIPTS/fix-snowpack-build

    #         - run: yarn dlx @yarnpkg/pnpify --sdk vscode
    #         - run: yarn format

    #         - run: yarn test
    #         - run: yarn build

    #         - run: |
    #               git config --global user.email "github-actions@users.noreply.github.com"
    #               git config --global user.name "github-actions"
    #               git add .
    #               git commit -m "[automated] Update template"
    #               git push origin HEAD --force

    template-snowpack-typescript:
        name: "template: snowpack-typescript"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 1

            - uses: actions/setup-node@v2
              with:
                  node-version: "14"

            - run: |
                  sudo mkdir -p $SCRIPTS
                  sudo cp -r scripts /var/svelte-template

            - run: git switch --orphan snowpack-typescript

            - run: |
                  mkdir /var/svelte-template/tmp
                  cd /var/svelte-template/tmp
                  yarn set version berry
                  yarn dlx create-snowpack-app . --template @snowpack/app-template-svelte-typescript --force --use-yarn
                  rm -rf .git

            - run: cp -r /var/svelte-template/tmp/* ./

            - run: |
                  cat >>.gitignore <<EOL

                  .yarn/*
                  !.yarn/cache
                  !.yarn/releases
                  !.yarn/plugins
                  !.yarn/sdks
                  !.yarn/versions
                  EOL
            - run: |
                  cat >>.gitattributes <<EOL
                  /.yarn/** linguist-vendored
                  EOL

            - run: |
                  yarn add -D svelte-hmr svelte-language-server @snowpack/plugin-webpack
                  yarn plugin import typescript
                  node $SCRIPTS/add-snowpack-plugins @snowpack/plugin-webpack
                  yarn dlx @yarnpkg/pnpify --sdk vscode

            - run: node $SCRIPTS/add-prettier
            - run: node $SCRIPTS/add-lint-staged
            - run: node $SCRIPTS/fix-snowpack-build

            - run: yarn dlx @yarnpkg/pnpify --sdk vscode
            - run: yarn format

            - run: yarn test
            - run: yarn build

            - run: |
                  git config --global user.email "github-actions@users.noreply.github.com"
                  git config --global user.name "github-actions"
                  git add .
                  git commit -m "[automated] Update template"
                  git push origin HEAD --force

    # template-snowpack-typescript-tailwind:
    #     name: "Template: snowpack-typescript-tailwind"
    #     runs-on: ubuntu-latest
    #     # needs: [template-snowpack-typescript]
    #     steps:
    #         - uses: actions/checkout@v2
    #           with:
    #               fetch-depth: 1

    #         - uses: actions/setup-node@v2
    #           with:
    #               node-version: "14"

    #         - run: |
    #               sudo mkdir -p $SCRIPTS
    #               sudo cp -r scripts /var/svelte-template

    #         - uses: actions/checkout@v2
    #           with:
    #               fetch-depth: 1
    #               ref: snowpack-typescript

    #         - run: git switch --force-create snowpack-typescript-tailwind

    #         - run: yarn add -D esbuild
    #         - run: node $SCRIPTS/setup-tailwind

    #         - run: yarn dlx @yarnpkg/pnpify --sdk vscode
    #         - run: yarn format

    #         - run: yarn test
    #         - run: yarn build

    #         - run: |
    #               git config --global user.email "github-actions@users.noreply.github.com"
    #               git config --global user.name "github-actions"
    #               git add .
    #               git commit -m "[automated] Update template"
    #               git push origin HEAD --force
